import React from "react";
import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/layout.module.css";
import ErrorBoundary from "../../utils/ErrorBoundary/ErrorBoundary";
type Props = { children: React.ReactNode; title?: string };

export default function Layout({ children, title = "" }: Props) {
  const [darkMode, setMode] = React.useState(false);

  return (
    <ErrorBoundary fallback={<p>Error loading page...refresh</p>}>
      <div
        className="  min-h-full my-2"
        style={{ minHeight: "100vh" }}
        data-theme={darkMode ? "dark" : "light"}
      >
        <Header title={title} />
        <nav
          data-testid="nav"
          className="flex flex-row justify-evenly items-center"
          style={navStyles("relative")}
        >
          <h2>Farmer Records.</h2>
          <button className="ml-5 " onClick={() => setMode((mode) => !mode)}>
            {darkMode ? "Light" : "Dark"}
          </button>
          <ul className="flex items-center justify-evenly mx-3">
            <li className="mx-2">
              <Link href="/">
                <a>Home</a>
              </Link>
            </li>
            <li className="mx-2">
              <Link href="/sign-up">
                <a>Sign up</a>
              </Link>
            </li>
            <li className="mx-2">
              <Link href="/login">
                <a>Login</a>
              </Link>
            </li>
          </ul>
        </nav>
        <main style={{ minHeight: "100vh" }}> {children}</main>

        <footer
          style={footerStyles()}
          className=" bg-purple-500 sm:bg-yellow-500  flex flex-row md:flex-col"
        >
          <p>Get a job!</p>
          <p> &copy; {new Date().getFullYear()}. All Rights Reserved.</p>
        </footer>
      </div>
    </ErrorBoundary>
  );
}

const Header: React.FC<{ title?: string }> = ({ title = "" }) => (
  <Head key="GenZ">
    <title>{title}</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="initial-scale=1, width=device-width" />

    <link rel="icon" href="/favicon.ico" />
  </Head>
);

const footerStyles = () => ({
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  padding: ".75rem",

  color: "white",
  marginLeft: ".75rem",
  lineHeight: "1.2",
});

const navStyles = (pos: "relative" | "fixed") => ({
  padding: ".25rem",
  background: "pink",
  color: "white",
  display: "flex",
  flexGrow: 1,
  justifyContent: "center",
  position: pos,
  top: 0,
  left: 0,
  height: 40,
  lineHeight: 1.2,
  right: 0,
  borderBottom: "1px solid #333",
  zIndex: 10,
  transform: "scale(1.0) skew(10deg)",
  transition: "all .5s ease",
});
